-- liquibase formatted sql

-- changeset iavdeyev:1

CREATE TABLE Owner
(
    chatId        TEXT    NOT NULL,
    name          TEXT    NOT NULL,
    phone_number  TEXT,
    shelterButton TEXT,
    reportButton  TEXT,
    volunteerChat BOOLEAN NOT NULL,
    CONSTRAINT pk_owner PRIMARY KEY (chatId)
);

-- changeset dlukin:2
CREATE TABLE pet
(
    id       BIGINT       NOT NULL,
    name_pet TEXT,
    owner_id TEXT   NOT NULL,
    kind     TEXT,
    CONSTRAINT pk_pets PRIMARY KEY (id )
);

ALTER TABLE pet
    ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES Owner (chatId);

-- changeset iavdeyev:3
CREATE TABLE report
(
    reportId         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recording_date   TEXT,
    photo            TEXT,
    diet             TEXT,
    state_of_health  TEXT,
    behavior_changes TEXT,
    pet              BIGINT,
    CONSTRAINT pk_report PRIMARY KEY (reportId)
);

ALTER TABLE report
    ADD CONSTRAINT FK_REPORT_ON_PET FOREIGN KEY (pet) REFERENCES pet (id);

-- changeset NataliShilova:4
CREATE TABLE Notification
(
    id        BIGINT  NOT NULL,
    text      TEXT    NOT NULL,
    messageId INTEGER NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);
