-- liquibase formatted sql

-- changeset iavdeyev:1

CREATE TABLE Owner
(
    chatId        TEXT    NOT NULL,
    name          TEXT    NOT NULL,
    phone_number  TEXT,
    shelterButton TEXT,
    reportButton  TEXT,
    volunteerChat BOOLEAN NOT NULL

);

-- changeset dlukin:2
CREATE TABLE pet
(
    id       BIGINT       NOT NULL,
    name_pet TEXT NOT NULL,
    owner_id TEXT,
    kind     TEXT NOT NULL

);

-- changeset iavdeyev:3
CREATE TABLE report
(
    reportId         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recording_date   DATE NOT NULL,
    photo            TEXT,
    diet             TEXT,
    state_of_health  TEXT,
    behavior_changes TEXT,
    pet              BIGINT NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (reportId)
);

-- changeset NataliShilova:4
CREATE TABLE Notification
(
    id        BIGINT  NOT NULL,
    text      TEXT    NOT NULL,
    messageId INTEGER NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);

ALTER TABLE report
    ADD check_report BOOLEAN;
ALTER TABLE pet
    ADD correct_report_count INTEGER;
ALTER TABLE pet
    ADD date_last_correct_report DATE;